destroy_environment workflow

diff --git a/.github/workflows/destroy-environment.yml b/.github/workflows/destroy-environment.yml
--- a/.github/workflows/destroy-environment.yml
+++ b/.github/workflows/destroy-environment.yml
@@ -20,147 +20,89 @@ concurrency: 1
 permissions:
   id-token: write # This is required for requesting the JWT
   contents: read # This is required for actions/checkout
-  pull-requests: write # This is required for pull request comments
 
 jobs:
-  destroy-cluster:
-    name: "Destroy Node Cluster Infrastructure"
-    runs-on: ubuntu-latest
+  identify-live-color:
+    name: "Check selected color is not live"
+    uses: ./.github/workflows/identify-live-color.yml
+    with:
+      dns_record_name: indexer.mainnet.vechain.org.
+      hosted_zone_id: Z058676337BU4AOFL6DMM
+    permissions:
+      contents: read
+      id-token: write
+    secrets: inherit
 
+  check-selected-color:
+    name: "Check selected color is not live"
+    runs-on: ubuntu-latest
+    needs: identify-live-color
+    steps:
+      - name: Check selected color is not live
+        run: |
+          if [ "${{ inputs.environment }}" == "${{ needs.identify-live-color.outputs.live_color }}" ]; then
+            echo "Selected color is live, aborting destruction."
+            exit 1
+          fi
+
+  destroy-environment:
+    name: "Destroy ${{ inputs.environment }} Infrastructure"
+    runs-on: ubuntu-latest
+    needs: [identify-live-color, check-selected-color]
+    if: ${{ inputs.environment }} == ${{ needs.identify-live-color.outputs.dead_color }}
     defaults:
       run:
-        working-directory: cluster
+        working-directory: terraform/api
 
     steps:
       - name: Checkout
         uses: actions/checkout@v3
 
-      - name: Get OpenID Connect Token
+      - name: Determine AWS account ID and role
+        id: account
         run: |
-          curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value' > /tmp/web_identity_token_file
+            if [ "${{ inputs.environment }}" == "prod" ]; then
+              echo "role_arn=${{ secrets.PROD_AWS_ACC_ROLE }}" >> $GITHUB_OUTPUT
+            else
+              echo "role_arn=${{ secrets.DEV_AWS_ACC_ROLE }}" >> $GITHUB_OUTPUT
+            fi
 
-      - name: Setup AWS credentials file
-        run: |
-          mkdir -p ~/.aws && cp ../config/credentials.aws ~/.aws/credentials && touch ~/.aws/config
-
-      - name: Validate AWS configuration
-        run: |
-          echo "AWS configuration checks:"
-          if (aws sts get-caller-identity) then
-            echo "[ERROR] - AWS credentials found. Please ensure there are no AWS credentials in order to use OpenID Connect." && exit 1
-          else
-            echo "[OK] - No AWS credentials found."
-          fi
-
-          if (env | grep AWS_) then
-            echo "[ERROR] - AWS environment variables found. Please ensure there are no AWS environment variables in order to use OpenID Connect." && exit 1
-          else 
-            echo "[OK] - No AWS environment variables found."
-          fi
-
-          credentials_file_path="$HOME/.aws/credentials"
-          if [ -f "$credentials_file_path" ] && grep -q "arn:aws:iam" "$credentials_file_path"; then
-            echo "[OK] - The file '$credentials_file_path' exists and contains the AWS IAM ARN."
-          elif [ -f "$credentials_file_path" ]; then
-            echo "[ERROR] - The file '$credentials_file_path' exists but does not contain the AWS IAM ARN. Have you configured it?" && exit 1
-          else
-            echo "[ERROR] - The file '$credentials_file_path' does not exist." && exit 1
-          fi
-
-      - name: Determine deployment target
-        run: |
-          if [ "${{ inputs.target_color }}" = "ci" ]; then
-            echo "Deployment target: '${{ inputs.target_color}}-${{ inputs.target_environment}}'." >> "$GITHUB_STEP_SUMMARY"
-            exit 0
-          fi
-
-          if [ "${{ inputs.target_environment }}" = "prod" ]; then
-            profile="prod-node-devops"
-          else
-            profile="node-devops"
-          fi
-
-          HOSTED_ZONE_ID=$(aws route53 list-hosted-zones --profile=$profile --query "HostedZones[?Name == '${{ env.FQDN }}.'].Id" --output text | sed 's#/hostedzone/##g')
-      # Required to access terraform modules from remote repositories
-      # e.g. github.com/vechainfoundation/terraform_infrastructure_modules
-      - name: Setup TERRAFORM_MODULES_PAT for cross-repo access
-        run: git config --global url."https://oauth2:${{ secrets.TERRAFORM_MODULES_PAT }}@github.com".insteadOf https://github.com
-
-      - name: Setup terraform
-        uses: hashicorp/setup-terraform@v2
-        if: inputs.target_color == env.STAGING_COLOR || inputs.target_color == 'ci'
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
         with:
-          terraform_version: 1.6
+            aws-region: eu-west-1
+            role-to-assume: ${{ steps.account.outputs.role_arn }}
 
-      - name: Initialize terraform
-        if: inputs.target_color == env.STAGING_COLOR || inputs.target_color == 'ci'
+      # Required for Terraform to source modules from other vechain repositories
+      - name: Set up SSH agent
+        uses: webfactory/ssh-agent@v0.8.0
+        with:
+          ssh-private-key: ${{ secrets.VECHAINCI_SSH_PRIVATE_KEYS }}
+
+      - name: Point backend to correct environment
+        id: specify-backend
+        run: |
+          sed -i "s/{{{ENV}}}/${{ inputs.environment }}/g" provider.tf
+        continue-on-error: false
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_version: 1.7.3
+          terraform_wrapper: true
+
+      - name: Terraform initialize
         id: init
         run: terraform init
 
-      - name: Select terraform workspace
-        if: inputs.target_color == env.STAGING_COLOR || inputs.target_color == 'ci'
+      - name: Terraform workspace
         id: workspace
-        run: terraform workspace select ${{ inputs.target_color }}-${{ inputs.target_environment }}
-
-      # The S3 buckets for ALB Access Logs and CloutTrail in production are delete-protected and not destroyed through terraform.
-      - name: Remove terraform delete-protected resources from state
-        if: inputs.target_color == env.STAGING_COLOR && inputs.target_environment == 'prod'
-        id: state
-        run: |
-          terraform state rm module.mainnet.aws_s3_bucket.lb_logs
-          terraform state rm module.testnet.aws_s3_bucket.lb_logs
-          terraform state rm module.cloudtrail.aws_s3_bucket.bucket
-        continue-on-error: true
+        run: terraform workspace select ${{ inputs.environment }}
 
       - name: Plan terraform destroy
-        if: inputs.target_color == env.STAGING_COLOR || inputs.target_color == 'ci'
         id: plan
-        run: terraform plan -out "destroy.plan" -destroy -no-color
+        run: terraform plan -out "destroy.plan" -destroy
 
       - name: Terraform destroy
-        if: inputs.target_color == env.STAGING_COLOR || inputs.target_color == 'ci'
         id: destroy
-        run: terraform apply "destroy.plan" -no-color
-
-      - name: Post comment to the pull request
-        uses: actions/github-script@v6
-        if: (inputs.target_color == env.STAGING_COLOR || inputs.target_color == 'ci') && (github.event_name == 'pull_request')
-        with:
-          script: |
-            // 1. Retrieve existing bot comments for the PR
-            const { data: comments } = await github.rest.issues.listComments({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              issue_number: context.issue.number,
-            })
-            const botComment = comments.find(comment => {
-              return comment.user.type === 'Bot' && comment.body.includes('Node Cluster Destruction Report: \`${{ inputs.target_color }}-${{ inputs.target_environment }}\`')
-            })
-
-            // 2. Prepare format of the comment
-            const output = `## :arrow_down: Node Cluster Destruction Report: \`${{ inputs.target_color }}-${{ inputs.target_environment }}\`
-
-            |                  Step                   |               Status              |
-            |-----------------------------------------|-----------------------------------|
-            | :gear: Terraform Initialization         | \`${{ steps.init.outcome }}\`     |
-            | :placard: Terraform Select Workspace    | \`${{ steps.workspace.outcome }}\`|
-            | :x: Terraform Destroy                   | \`${{ steps.destroy.outcome }}\`  |
-
-            > Workflow \`${{ github.workflow }}\` triggered by @${{ github.actor }}. For more details [go to the workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).`;
-
-            // 3. If we have a comment, update it, otherwise create a new one
-            if (botComment) {
-              github.rest.issues.updateComment({
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                comment_id: botComment.id,
-                body: output
-              })
-            } else {
-              github.rest.issues.createComment({
-                issue_number: context.issue.number,
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                body: output
-              })
-            }
+        run: terraform apply "destroy.plan"
