Cicd align indexer workflows (#648)
Co-authored-by: Dougal Rea <73436291+dougalrea@users.noreply.github.com>
Co-authored-by: Rishi Pal <rishi.pal@vechain.org>
Co-authored-by: Hamza Abdullahi <173275643+HamzaAbdullah-V@users.noreply.github.com>
Co-authored-by: Roisin Dowling <55144940+roisindowling@users.noreply.github.com>
Co-authored-by: roisindowling <roisin.dowling@vechain.org>

diff --git a/.github/workflows/destroy-environment.yml b/.github/workflows/destroy-environment.yml
--- a/.github/workflows/destroy-environment.yml
+++ b/.github/workflows/destroy-environment.yml
@@ -1,17 +1,7 @@
-name: Cluster Destroy
+name: Destroy Dead Environment
 
 on:
   workflow_dispatch:
-    inputs:
-      environment:
-        description: "The environment to destroy"
-        required: true
-        default: dev
-        type: choice
-        options:
-          - dev
-          - prod-blue
-          - prod-green
 
 # Prevent parallel deploy/destroy of the node cluster infrastructure in the same workspace
 concurrency: 1
@@ -21,128 +11,112 @@ permissions:
   id-token: write  # This is required for requesting the JWT
   contents: read   # This is required for actions/checkout
 
+env:
+  INDEXER: "veworld"
+
 jobs:
   identify-live-color:
     name: "Identify live and dead colors"
     uses: ./.github/workflows/identify-live-color.yml
     with:
-      dns_record_mainnet_name: mainnet.live.prod.veworld.vechain.org.
-      dns_record_testnet_name: testnet.live.prod.veworld.vechain.org.
+      dns_record_mainnet_name: mainnet.live.prod.${{ env.INDEXER }}.vechain.org.
+      dns_record_testnet_name: testnet.live.prod.${{ env.INDEXER }}.vechain.org.
       hosted_zone_id: Z08093993BM56HB3DD4U4
     permissions:
       contents: read
       id-token: write
     secrets: inherit
 
-  check-selected-color:
-    name: "Check color selected for destruction is not live"
-    runs-on: ubuntu-latest
-    needs: [identify-live-color]
-    steps:
-      - name: Check selected color is not live
-        run: |
-          if [ "${{ inputs.environment }}" == "${{ needs.identify-live-color.outputs.mainnet_live_color }}" ]; then
-            echo "Selected color is live, aborting destruction."
-            exit 1
-          fi
-
   destroy-lingering-resources:
     name: Destroy Lingering Resources
-    needs: [identify-live-color, check-selected-color]
+    needs: [identify-live-color]
     runs-on: ubuntu-latest
     env:
       dead_color: ${{ needs.identify-live-color.outputs.mainnet_dead_color }}
-      account: ${{ startsWith(inputs.environment, 'prod-') && 'prod' || 'dev' }}
     steps:
-      - name: Determine AWS account ID and role
-        id: account
+      - name: Check mainnet and testnet on same colour
+        id: check-net-color
         run: |
-            if [ "${{ env.account }}" == "prod" ]; then
-              echo "role_arn=${{ secrets.PROD_AWS_ACC_ROLE }}" >> $GITHUB_OUTPUT
-            else
-              echo "role_arn=${{ secrets.DEV_AWS_ACC_ROLE }}" >> $GITHUB_OUTPUT
-            fi
+          if [ "${{ needs.identify-live-color.outputs.mainnet_dead_color }}" != "${{ needs.identify-live-color.outputs.testnet_dead_color }}" ]; then
+            echo "Mainnet and Testnet colours are not the same, aborting destruction."
+            exit 1
+          fi
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
-          aws-region: eu-west-1
-          role-to-assume: ${{ steps.account.outputs.role_arn }}
+            aws-region: eu-west-1
+            role-to-assume: ${{ secrets.AWS_ACC_ROLE }}
 
       - name: Destroy Lingering Secrets
         run: |
           echo "Deleting lingering secrets..."
-          aws secretsmanager delete-secret --secret-id /${{ env.dead_color }}/veworld/mongo_api_password --force-delete-without-recovery || true
-          aws secretsmanager delete-secret --secret-id /${{ env.dead_color }}/veworld/mongo_indexer_password --force-delete-without-recovery || true
+          aws secretsmanager delete-secret --secret-id /${{ env.dead_color }}/${{ env.INDEXER }}/mongo_api_password --force-delete-without-recovery || true
+          aws secretsmanager delete-secret --secret-id /${{ env.dead_color }}/${{ env.INDEXER }}/mongo_indexer_password --force-delete-without-recovery || true
 
       - name: "Destroy LB Logs S3 Buckets"
         run: |
           echo "Deleting LB logs S3 buckets..."
-          aws s3 rb s3://${{ env.dead_color }}-veworld-main-api-ecs-lb-bucket --force || true
-          aws s3 rb s3://${{ env.dead_color }}-veworld-test-api-ecs-lb-bucket --force || true
+          buckets=("s3://${{ env.dead_color }}-${{ env.INDEXER }}-main-api-ecs-lb-bucket" "s3://${{ env.dead_color }}-${{ env.INDEXER }}-test-api-ecs-lb-bucket")
+          for bucket in "${buckets[@]}"; do
+            if aws s3 ls "${bucket}" 2>&1 | grep -q 'NoSuchBucket'; then
+              echo "Bucket $bucket not found, skipping."
+            else
+              echo "Bucket $bucket found, deleting..."
+              aws s3api delete-bucket-lifecycle --bucket "$bucket" || true
+              aws s3 rb "$bucket" --force || true
+            fi
+          done
 
       - name: "Destroy Load Balancers"
         run: |
           echo "Fetching load balancer ARNs..."
-          dead_main_lb_arn=$(aws elbv2 describe-load-balancers --query "LoadBalancers[?contains(LoadBalancerName, '${{ env.dead_color }}-main-api-veworld-alb')].LoadBalancerArn" --output text) || true
-          dead_test_lb_arn=$(aws elbv2 describe-load-balancers --query "LoadBalancers[?contains(LoadBalancerName, '${{ env.dead_color }}-test-api-veworld-alb')].LoadBalancerArn" --output text) || true
+          dead_main_api_lb_arn=$(aws elbv2 describe-load-balancers --query "LoadBalancers[?contains(LoadBalancerName, '${{ env.dead_color }}-main-api-${{ env.INDEXER }}-alb')].LoadBalancerArn" --output text) || true
+          dead_test_api_lb_arn=$(aws elbv2 describe-load-balancers --query "LoadBalancers[?contains(LoadBalancerName, '${{ env.dead_color }}-test-api-${{ env.INDEXER }}-alb')].LoadBalancerArn" --output text) || true
 
-          if [ ! -z "$dead_main_lb_arn" ]; then
-            echo "Disabling deletion protection for main load balancer..."
-            aws elbv2 modify-load-balancer-attributes --load-balancer-arn $dead_main_lb_arn --attributes Key=deletion_protection.enabled,Value=false || true
-            echo "Destroying main load balancer..."
-            aws elbv2 delete-load-balancer --load-balancer-arn $dead_main_lb_arn || true
+          if [ ! -z "$dead_main_api_lb_arn" ]; then
+            echo "Disabling deletion protection for main API load balancer..."
+            aws elbv2 modify-load-balancer-attributes --load-balancer-arn $dead_main_api_lb_arn --attributes Key=deletion_protection.enabled,Value=false || true
+            echo "Destroying main API load balancer..."
+            aws elbv2 delete-load-balancer --load-balancer-arn $dead_main_api_lb_arn || true
           fi
 
-          if [ ! -z "$dead_test_lb_arn" ]; then
-            echo "Disabling deletion protection for test load balancer..."
-            aws elbv2 modify-load-balancer-attributes --load-balancer-arn $dead_test_lb_arn --attributes Key=deletion_protection.enabled,Value=false || true
-            echo "Destroying test load balancer..."
-            aws elbv2 delete-load-balancer --load-balancer-arn $dead_test_lb_arn || true
+          if [ ! -z "$dead_test_api_lb_arn" ]; then
+            echo "Disabling deletion protection for test API load balancer..."
+            aws elbv2 modify-load-balancer-attributes --load-balancer-arn $dead_test_api_lb_arn --attributes Key=deletion_protection.enabled,Value=false || true
+            echo "Destroying test API load balancer..."
+            aws elbv2 delete-load-balancer --load-balancer-arn $dead_test_api_lb_arn || true
           fi
 
   destroy-environment:
-    name: "Destroy ${{ inputs.environment }} Infrastructure"
+    name: "Destroy Terraform Infrastructure"
     runs-on: ubuntu-latest
-    needs: [identify-live-color, check-selected-color, destroy-lingering-resources]
-    if: ${{ inputs.environment }} == ${{ needs.identify-live-color.outputs.mainnet_dead_color }}
+    needs: [identify-live-color, destroy-lingering-resources]
+    env:
+      dead_color: ${{ needs.identify-live-color.outputs.mainnet_dead_color }}
+
     defaults:
       run:
         working-directory: terraform/api
 
-    env:
-      account: ${{ startsWith(inputs.environment, 'prod-') && 'prod' || 'dev' }}
-
     steps:
+      - name: Show dead color
+        run: echo "destroying dead environment - ${{ env.dead_color }}"
+
       - name: Checkout
         uses: actions/checkout@v3
-
-      - name: Determine AWS account ID and role
-        id: account
-        run: |
-            if [ "${{ env.account }}" == "prod" ]; then
-              echo "role_arn=${{ secrets.PROD_AWS_ACC_ROLE }}" >> $GITHUB_OUTPUT
-            else
-              echo "role_arn=${{ secrets.DEV_AWS_ACC_ROLE }}" >> $GITHUB_OUTPUT
-            fi
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
-          aws-region: eu-west-1
-          role-to-assume: ${{ steps.account.outputs.role_arn }}
+            aws-region: eu-west-1
+            role-to-assume: ${{ secrets.AWS_ACC_ROLE }}
 
       # Required for Terraform to source modules from other vechain repositories
       - name: Set up SSH agent
         uses: webfactory/ssh-agent@v0.8.0
         with:
           ssh-private-key: ${{ secrets.VECHAINCI_SSH_PRIVATE_KEYS }}
-
-      - name: Point backend to correct environment
-        id: specify-backend
-        run: |
-          sed -i "s/{{{ENV}}}/${{ env.account }}/g" provider.tf
-        continue-on-error: false
 
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v2
@@ -152,11 +126,19 @@ jobs:
 
       - name: Terraform initialize
         id: init
-        run: terraform init -backend-config="environments/${{ inputs.environment }}.config" -reconfigure
+        run: terraform init -backend-config="environments/${{ env.dead_color }}.config" -reconfigure
 
       - name: Terraform workspace
         id: workspace
-        run: terraform workspace select ${{ inputs.environment }}
+        run: terraform workspace select ${{ env.dead_color }}
+
+      - name: Clear s3 lifecycle configs via cli 
+        run: |
+          aws s3api delete-bucket-lifecycle --bucket "${{ env.dead_color }}-${{ env.INDEXER }}-main-api-ecs-lb-bucket"
+          aws s3api delete-bucket-lifecycle --bucket "${{ env.dead_color }}-${{ env.INDEXER }}-test-api-ecs-lb-bucket"
+
+      - name: Show resources to be destroyed
+        run: terraform state list
 
       - name: Show s3 lifecycle config from state
         run: terraform state list | grep aws_s3_bucket_lifecycle_configuration
