adding testnet_live_color

diff --git a/.github/workflows/identify-live-color.yml b/.github/workflows/identify-live-color.yml
--- a/.github/workflows/identify-live-color.yml
+++ b/.github/workflows/identify-live-color.yml
@@ -21,11 +21,16 @@ on:
         value: ${{ jobs.identify-live.outputs.dead_color }}
   workflow_dispatch:
     inputs:
-      dns_record_name:
-        description: "The DNS record value to check"
+      dns_record_mainnet_name:
+        description: "The mainnet DNS record value to check"
         required: true
         type: string
         default: "mainnet.live.prod.veworld.vechain.org."
+      dns_record_testnet_name:
+        description: "The testnet DNS record value to check"
+        required: true
+        type: string
+        default: "testnet.live.prod.veworld.vechain.org."
       hosted_zone_id:
         description: "The hosted zone ID of the DNS record"
         required: true
@@ -59,19 +64,35 @@ jobs:
       - name: Get DNS record value
         id: get_dns_value
         run: |
-          dns_value=$(aws route53 list-resource-record-sets --hosted-zone-id ${{ inputs.hosted_zone_id }} --query "ResourceRecordSets[?Name == '${{ inputs.dns_record_name }}'].ResourceRecords[].Value" --output text)
-          echo "dns_value=${dns_value}"
-          echo "dns_value=${dns_value}" >> $GITHUB_OUTPUT
+          dns_mainnet_value=$(aws route53 list-resource-record-sets --hosted-zone-id ${{ inputs.hosted_zone_id }} --query "ResourceRecordSets[?Name == '${{ inputs.dns_record_mainnet_name }}'].ResourceRecords[].Value" --output text)
+          dns_testnet_value=$(aws route53 list-resource-record-sets --hosted-zone-id ${{ inputs.hosted_zone_id }} --query "ResourceRecordSets[?Name == '${{ inputs.dns_record_testnet_name }}'].ResourceRecords[].Value" --output text)
+
+          echo "dns_mainnet_value=${dns_mainnet_value}"
+          echo "dns_mainnet_value=${dns_mainnet_value}" >> $GITHUB_OUTPUT
+
+          echo "dns_testnet_value=${dns_testnet_value}"
+          echo "dns_testnet_value=${dns_testnet_value}" >> $GITHUB_OUTPUT
 
       - name: Define output variables
         id: define_color_vars
         run: |
-          if [[ "${{ steps.get_dns_value.outputs.dns_value }}" == prod-blue* ]]; then
-            echo "live_color=prod-blue" >> $GITHUB_OUTPUT
-            echo "dead_color=prod-green" >> $GITHUB_OUTPUT
-          elif [[ "${{ steps.get_dns_value.outputs.dns_value }}" == prod-green* ]]; then
-            echo "live_color=prod-green" >> $GITHUB_OUTPUT
-            echo "dead_color=prod-blue" >> $GITHUB_OUTPUT
+          if [[ "${{ steps.get_dns_value.outputs.dns_mainnet_value }}" == prod-blue* ]]; then
+            echo "mainnet_live_color=prod-blue" >> $GITHUB_OUTPUT
+            echo "mainnet_dead_color=prod-green" >> $GITHUB_OUTPUT
+          elif [[ "${{ steps.get_dns_value.outputs.dns_mainnet_value }}" == prod-green* ]]; then
+            echo "mainnet_live_color=prod-green" >> $GITHUB_OUTPUT
+            echo "mainnet_dead_color=prod-blue" >> $GITHUB_OUTPUT
+          else
+            echo "Error: DNS record value does not match expected patterns (prod-blue* or prod-green*)"
+            exit 1
+          fi
+
+           if [[ "${{ steps.get_dns_value.outputs.dns_testnet_value }}" == prod-blue* ]]; then
+            echo "testnet_live_color=prod-blue" >> $GITHUB_OUTPUT
+            echo "testnet_dead_color=prod-green" >> $GITHUB_OUTPUT
+          elif [[ "${{ steps.get_dns_value.outputs.dns_testnet_value }}" == prod-green* ]]; then
+            echo "testnet_live_color=prod-green" >> $GITHUB_OUTPUT
+            echo "testnet_dead_color=prod-blue" >> $GITHUB_OUTPUT
           else
             echo "Error: DNS record value does not match expected patterns (prod-blue* or prod-green*)"
             exit 1
@@ -79,10 +100,14 @@ jobs:
       
       - name: Output live/dead color environments
         run: |
-          echo "Live color environment is ${{ steps.define_color_vars.outputs.live_color }}"
-          echo "Dead color environment is ${{ steps.define_color_vars.outputs.dead_color }}"
+          echo "Live color for mainnent environment is ${{ steps.define_color_vars.outputs.mainnet_live_color }}"
+          echo "Dead color for mainnet environment is ${{ steps.define_color_vars.outputs.mainnet_dead_color }}"
+          echo "Live color for testnet environment is ${{ steps.define_color_vars.outputs.testnet_live_color }}"
+          echo "Dead color for testnet environment is ${{ steps.define_color_vars.outputs.testnet_dead_color }}"
 
     # Define the outputs section to pass data back to the calling workflow
     outputs:
-      live_color: ${{ steps.define_color_vars.outputs.live_color }}
-      dead_color: ${{ steps.define_color_vars.outputs.dead_color }}
+      mainnet_live_color: ${{ steps.define_color_vars.outputs.mainnet_live_color }}
+      mainnet_dead_color: ${{ steps.define_color_vars.outputs.mainnet_dead_color }}
+      testnet_live_color: ${{ steps.define_color_vars.outputs.testnet_live_color }}
+      testnet_dead_color: ${{ steps.define_color_vars.outputs.testnet_dead_color }}
